export const SEARCH_STORES_BY_POSTCODE = 'SEARCH_STORES_BY_POSTCODE';
export const SEARCH_STORES_NEAR_ME = 'SEARCH_STORES_NEAR_ME';
export const FETCH_STORES_REQUEST = 'FETCH_STORES_REQUEST';
export const FETCH_STORES_FAILURE = 'FETCH_STORES_FAILURE';
export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';
